/*
 * Payments API
 *  The payments API allows you to initiate and manage payments and vendors from your Brex business accounts. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Money;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BankConnectionAvailableBalance
 */
public class BankConnectionAvailableBalanceTest {
    private final BankConnectionAvailableBalance model = new BankConnectionAvailableBalance();

    /**
     * Model tests for BankConnectionAvailableBalance
     */
    @Test
    public void testBankConnectionAvailableBalance() {
        // TODO: test BankConnectionAvailableBalance
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'asOfDate'
     */
    @Test
    public void asOfDateTest() {
        // TODO: test asOfDate
    }

}
