/*
 * Payments API
 *  The payments API allows you to initiate and manage payments and vendors from your Brex business accounts. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BankConnectionAvailableBalance;
import com.konfigthis.client.model.BankDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BankConnection
 */
public class BankConnectionTest {
    private final BankConnection model = new BankConnection();

    /**
     * Model tests for BankConnection
     */
    @Test
    public void testBankConnection() {
        // TODO: test BankConnection
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'bankDetails'
     */
    @Test
    public void bankDetailsTest() {
        // TODO: test bankDetails
    }

    /**
     * Test the property 'brexAccountId'
     */
    @Test
    public void brexAccountIdTest() {
        // TODO: test brexAccountId
    }

    /**
     * Test the property 'lastFour'
     */
    @Test
    public void lastFourTest() {
        // TODO: test lastFour
    }

    /**
     * Test the property 'availableBalance'
     */
    @Test
    public void availableBalanceTest() {
        // TODO: test availableBalance
    }

    /**
     * Test the property 'currentBalance'
     */
    @Test
    public void currentBalanceTest() {
        // TODO: test currentBalance
    }

}
