/*
 * Payments API
 *  The payments API allows you to initiate and manage payments and vendors from your Brex business accounts. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BeneficiaryBank;
import com.konfigthis.client.model.CounterPartyResponseType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BankAccountDetailsResponseAllOf
 */
public class BankAccountDetailsResponseAllOfTest {
    private final BankAccountDetailsResponseAllOf model = new BankAccountDetailsResponseAllOf();

    /**
     * Model tests for BankAccountDetailsResponseAllOf
     */
    @Test
    public void testBankAccountDetailsResponseAllOf() {
        // TODO: test BankAccountDetailsResponseAllOf
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'routingNumber'
     */
    @Test
    public void routingNumberTest() {
        // TODO: test routingNumber
    }

    /**
     * Test the property 'accountNumber'
     */
    @Test
    public void accountNumberTest() {
        // TODO: test accountNumber
    }

    /**
     * Test the property 'beneficiaryBank'
     */
    @Test
    public void beneficiaryBankTest() {
        // TODO: test beneficiaryBank
    }

    /**
     * Test the property 'fedReferenceNumber'
     */
    @Test
    public void fedReferenceNumberTest() {
        // TODO: test fedReferenceNumber
    }

    /**
     * Test the property 'externalMemo'
     */
    @Test
    public void externalMemoTest() {
        // TODO: test externalMemo
    }

}
