/*
 * Payments API
 *  The payments API allows you to initiate and manage payments and vendors from your Brex business accounts. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Address;
import com.konfigthis.client.model.PaymentDetailsTypeRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ChequeDetailsRequestAllOf
 */
public class ChequeDetailsRequestAllOfTest {
    private final ChequeDetailsRequestAllOf model = new ChequeDetailsRequestAllOf();

    /**
     * Model tests for ChequeDetailsRequestAllOf
     */
    @Test
    public void testChequeDetailsRequestAllOf() {
        // TODO: test ChequeDetailsRequestAllOf
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'mailingAddress'
     */
    @Test
    public void mailingAddressTest() {
        // TODO: test mailingAddress
    }

    /**
     * Test the property 'recipientName'
     */
    @Test
    public void recipientNameTest() {
        // TODO: test recipientName
    }

    /**
     * Test the property 'beneficiaryName'
     */
    @Test
    public void beneficiaryNameTest() {
        // TODO: test beneficiaryName
    }

}
