/*
 * Payments API
 *  The payments API allows you to initiate and manage payments and vendors from your Brex business accounts. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Address;
import com.konfigthis.client.model.PaymentDetailsTypeResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ChequeDetailsResponseAllOf
 */
public class ChequeDetailsResponseAllOfTest {
    private final ChequeDetailsResponseAllOf model = new ChequeDetailsResponseAllOf();

    /**
     * Model tests for ChequeDetailsResponseAllOf
     */
    @Test
    public void testChequeDetailsResponseAllOf() {
        // TODO: test ChequeDetailsResponseAllOf
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'paymentInstrumentId'
     */
    @Test
    public void paymentInstrumentIdTest() {
        // TODO: test paymentInstrumentId
    }

    /**
     * Test the property 'mailingAddress'
     */
    @Test
    public void mailingAddressTest() {
        // TODO: test mailingAddress
    }

    /**
     * Test the property 'recipientName'
     */
    @Test
    public void recipientNameTest() {
        // TODO: test recipientName
    }

}
