/*
 * Payments API
 *  The payments API allows you to initiate and manage payments and vendors from your Brex business accounts. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Address;
import com.konfigthis.client.model.PaymentDetailsTypeResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InternationalWireDetailsResponse
 */
public class InternationalWireDetailsResponseTest {
    private final InternationalWireDetailsResponse model = new InternationalWireDetailsResponse();

    /**
     * Model tests for InternationalWireDetailsResponse
     */
    @Test
    public void testInternationalWireDetailsResponse() {
        // TODO: test InternationalWireDetailsResponse
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'paymentInstrumentId'
     */
    @Test
    public void paymentInstrumentIdTest() {
        // TODO: test paymentInstrumentId
    }

    /**
     * Test the property 'swiftCode'
     */
    @Test
    public void swiftCodeTest() {
        // TODO: test swiftCode
    }

    /**
     * Test the property 'iban'
     */
    @Test
    public void ibanTest() {
        // TODO: test iban
    }

    /**
     * Test the property 'beneficiaryBankName'
     */
    @Test
    public void beneficiaryBankNameTest() {
        // TODO: test beneficiaryBankName
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

}
