/*
 * Payments API
 *  The payments API allows you to initiate and manage payments and vendors from your Brex business accounts. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OriginatingAccountResponseType
 */
public class OriginatingAccountResponseTypeTest {
    /**
     * Model tests for OriginatingAccountResponseType
     */
    @Test
    public void testOriginatingAccountResponseType() {
        // TODO: test OriginatingAccountResponseType
    }

}
