/*
 * Payments API
 *  The payments API allows you to initiate and manage payments and vendors from your Brex business accounts. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Money;
import com.konfigthis.client.model.PaymentType;
import com.konfigthis.client.model.TransferCancellationReason;
import com.konfigthis.client.model.TransferStatus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Transfer
 */
public class TransferTest {
    private final Transfer model = new Transfer();

    /**
     * Model tests for Transfer
     */
    @Test
    public void testTransfer() {
        // TODO: test Transfer
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'counterparty'
     */
    @Test
    public void counterpartyTest() {
        // TODO: test counterparty
    }

    /**
     * Test the property 'paymentType'
     */
    @Test
    public void paymentTypeTest() {
        // TODO: test paymentType
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'processDate'
     */
    @Test
    public void processDateTest() {
        // TODO: test processDate
    }

    /**
     * Test the property 'originatingAccount'
     */
    @Test
    public void originatingAccountTest() {
        // TODO: test originatingAccount
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'cancellationReason'
     */
    @Test
    public void cancellationReasonTest() {
        // TODO: test cancellationReason
    }

    /**
     * Test the property 'estimatedDeliveryDate'
     */
    @Test
    public void estimatedDeliveryDateTest() {
        // TODO: test estimatedDeliveryDate
    }

    /**
     * Test the property 'creatorUserId'
     */
    @Test
    public void creatorUserIdTest() {
        // TODO: test creatorUserId
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'externalMemo'
     */
    @Test
    public void externalMemoTest() {
        // TODO: test externalMemo
    }

}
