/*
 * Payments API
 *  The payments API allows you to initiate and manage payments and vendors from your Brex business accounts. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Specifies the approval type for the transaction.  &#x60;MANUAL&#x60; requires a cash admin to approve the transaction before disbursing funds.  When not set, the default policy will apply.
 */
@JsonAdapter(ApprovalType.Adapter.class)public enum ApprovalType {
  
  MANUAL("MANUAL");

  private String value;

  ApprovalType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ApprovalType fromValue(String value) {
    for (ApprovalType b : ApprovalType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ApprovalType> {
    @Override
    public void write(final JsonWriter jsonWriter, final ApprovalType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ApprovalType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ApprovalType.fromValue(value);
    }
  }
}

