/*
 * Payments API
 *  The payments API allows you to initiate and manage payments and vendors from your Brex business accounts. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BeneficiaryBank;
import com.konfigthis.client.model.CounterPartyResponseType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * BankAccountDetailsResponseAllOf
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class BankAccountDetailsResponseAllOf {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private CounterPartyResponseType type;

  public static final String SERIALIZED_NAME_ROUTING_NUMBER = "routing_number";
  @SerializedName(SERIALIZED_NAME_ROUTING_NUMBER)
  private String routingNumber;

  public static final String SERIALIZED_NAME_ACCOUNT_NUMBER = "account_number";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_NUMBER)
  private String accountNumber;

  public static final String SERIALIZED_NAME_BENEFICIARY_BANK = "beneficiary_bank";
  @SerializedName(SERIALIZED_NAME_BENEFICIARY_BANK)
  private BeneficiaryBank beneficiaryBank;

  public static final String SERIALIZED_NAME_FED_REFERENCE_NUMBER = "fed_reference_number";
  @SerializedName(SERIALIZED_NAME_FED_REFERENCE_NUMBER)
  private String fedReferenceNumber;

  public static final String SERIALIZED_NAME_EXTERNAL_MEMO = "external_memo";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_MEMO)
  private String externalMemo;

  public BankAccountDetailsResponseAllOf() {
  }

  public BankAccountDetailsResponseAllOf description(String description) {
    
    
    
    
    this.description = description;
    return this;
  }

   /**
   * Description of the transfer.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Description of the transfer.")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    
    
    
    this.description = description;
  }


  public BankAccountDetailsResponseAllOf type(CounterPartyResponseType type) {
    
    
    
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public CounterPartyResponseType getType() {
    return type;
  }


  public void setType(CounterPartyResponseType type) {
    
    
    
    this.type = type;
  }


  public BankAccountDetailsResponseAllOf routingNumber(String routingNumber) {
    
    
    
    
    this.routingNumber = routingNumber;
    return this;
  }

   /**
   * Routing number of a bank account (or SWIFT/BIC code for international transfer). For incoming cheques, this field might be null.
   * @return routingNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Routing number of a bank account (or SWIFT/BIC code for international transfer). For incoming cheques, this field might be null.")

  public String getRoutingNumber() {
    return routingNumber;
  }


  public void setRoutingNumber(String routingNumber) {
    
    
    
    this.routingNumber = routingNumber;
  }


  public BankAccountDetailsResponseAllOf accountNumber(String accountNumber) {
    
    
    
    
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * Account number of a bank account (or IBAN code for international transfer). For incoming cheques, this field might be null.
   * @return accountNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Account number of a bank account (or IBAN code for international transfer). For incoming cheques, this field might be null.")

  public String getAccountNumber() {
    return accountNumber;
  }


  public void setAccountNumber(String accountNumber) {
    
    
    
    this.accountNumber = accountNumber;
  }


  public BankAccountDetailsResponseAllOf beneficiaryBank(BeneficiaryBank beneficiaryBank) {
    
    
    
    
    this.beneficiaryBank = beneficiaryBank;
    return this;
  }

   /**
   * Get beneficiaryBank
   * @return beneficiaryBank
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BeneficiaryBank getBeneficiaryBank() {
    return beneficiaryBank;
  }


  public void setBeneficiaryBank(BeneficiaryBank beneficiaryBank) {
    
    
    
    this.beneficiaryBank = beneficiaryBank;
  }


  public BankAccountDetailsResponseAllOf fedReferenceNumber(String fedReferenceNumber) {
    
    
    
    
    this.fedReferenceNumber = fedReferenceNumber;
    return this;
  }

   /**
   * Fed reference number for incoming wires
   * @return fedReferenceNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Fed reference number for incoming wires")

  public String getFedReferenceNumber() {
    return fedReferenceNumber;
  }


  public void setFedReferenceNumber(String fedReferenceNumber) {
    
    
    
    this.fedReferenceNumber = fedReferenceNumber;
  }


  public BankAccountDetailsResponseAllOf externalMemo(String externalMemo) {
    
    
    
    
    this.externalMemo = externalMemo;
    return this;
  }

   /**
   * External Memo populated by the sender
   * @return externalMemo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "External Memo populated by the sender")

  public String getExternalMemo() {
    return externalMemo;
  }


  public void setExternalMemo(String externalMemo) {
    
    
    
    this.externalMemo = externalMemo;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the BankAccountDetailsResponseAllOf instance itself
   */
  public BankAccountDetailsResponseAllOf putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankAccountDetailsResponseAllOf bankAccountDetailsResponseAllOf = (BankAccountDetailsResponseAllOf) o;
    return Objects.equals(this.description, bankAccountDetailsResponseAllOf.description) &&
        Objects.equals(this.type, bankAccountDetailsResponseAllOf.type) &&
        Objects.equals(this.routingNumber, bankAccountDetailsResponseAllOf.routingNumber) &&
        Objects.equals(this.accountNumber, bankAccountDetailsResponseAllOf.accountNumber) &&
        Objects.equals(this.beneficiaryBank, bankAccountDetailsResponseAllOf.beneficiaryBank) &&
        Objects.equals(this.fedReferenceNumber, bankAccountDetailsResponseAllOf.fedReferenceNumber) &&
        Objects.equals(this.externalMemo, bankAccountDetailsResponseAllOf.externalMemo)&&
        Objects.equals(this.additionalProperties, bankAccountDetailsResponseAllOf.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, type, routingNumber, accountNumber, beneficiaryBank, fedReferenceNumber, externalMemo, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankAccountDetailsResponseAllOf {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    routingNumber: ").append(toIndentedString(routingNumber)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    beneficiaryBank: ").append(toIndentedString(beneficiaryBank)).append("\n");
    sb.append("    fedReferenceNumber: ").append(toIndentedString(fedReferenceNumber)).append("\n");
    sb.append("    externalMemo: ").append(toIndentedString(externalMemo)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("description");
    openapiFields.add("type");
    openapiFields.add("routing_number");
    openapiFields.add("account_number");
    openapiFields.add("beneficiary_bank");
    openapiFields.add("fed_reference_number");
    openapiFields.add("external_memo");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("type");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to BankAccountDetailsResponseAllOf
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!BankAccountDetailsResponseAllOf.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BankAccountDetailsResponseAllOf is not found in the empty JSON string", BankAccountDetailsResponseAllOf.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BankAccountDetailsResponseAllOf.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("description").isJsonNull() && (jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if (!jsonObj.get("routing_number").isJsonNull() && (jsonObj.get("routing_number") != null && !jsonObj.get("routing_number").isJsonNull()) && !jsonObj.get("routing_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `routing_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("routing_number").toString()));
      }
      if (!jsonObj.get("account_number").isJsonNull() && (jsonObj.get("account_number") != null && !jsonObj.get("account_number").isJsonNull()) && !jsonObj.get("account_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `account_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("account_number").toString()));
      }
      // validate the optional field `beneficiary_bank`
      if (jsonObj.get("beneficiary_bank") != null && !jsonObj.get("beneficiary_bank").isJsonNull()) {
        BeneficiaryBank.validateJsonObject(jsonObj.getAsJsonObject("beneficiary_bank"));
      }
      if (!jsonObj.get("fed_reference_number").isJsonNull() && (jsonObj.get("fed_reference_number") != null && !jsonObj.get("fed_reference_number").isJsonNull()) && !jsonObj.get("fed_reference_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fed_reference_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fed_reference_number").toString()));
      }
      if (!jsonObj.get("external_memo").isJsonNull() && (jsonObj.get("external_memo") != null && !jsonObj.get("external_memo").isJsonNull()) && !jsonObj.get("external_memo").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `external_memo` to be a primitive type in the JSON string but got `%s`", jsonObj.get("external_memo").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BankAccountDetailsResponseAllOf.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BankAccountDetailsResponseAllOf' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BankAccountDetailsResponseAllOf> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BankAccountDetailsResponseAllOf.class));

       return (TypeAdapter<T>) new TypeAdapter<BankAccountDetailsResponseAllOf>() {
           @Override
           public void write(JsonWriter out, BankAccountDetailsResponseAllOf value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public BankAccountDetailsResponseAllOf read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             BankAccountDetailsResponseAllOf instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BankAccountDetailsResponseAllOf given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BankAccountDetailsResponseAllOf
  * @throws IOException if the JSON string is invalid with respect to BankAccountDetailsResponseAllOf
  */
  public static BankAccountDetailsResponseAllOf fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BankAccountDetailsResponseAllOf.class);
  }

 /**
  * Convert an instance of BankAccountDetailsResponseAllOf to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

