/*
 * Payments API
 *  The payments API allows you to initiate and manage payments and vendors from your Brex business accounts. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets CounterPartyType
 */
@JsonAdapter(CounterPartyType.Adapter.class)public enum CounterPartyType {
  
  VENDOR("VENDOR"),
  
  BOOK_TRANSFER("BOOK_TRANSFER");

  private String value;

  CounterPartyType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CounterPartyType fromValue(String value) {
    for (CounterPartyType b : CounterPartyType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<CounterPartyType> {
    @Override
    public void write(final JsonWriter jsonWriter, final CounterPartyType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CounterPartyType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CounterPartyType.fromValue(value);
    }
  }
}

