/*
 * Payments API
 *  The payments API allows you to initiate and manage payments and vendors from your Brex business accounts. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets OriginatingAccountResponseType
 */
@JsonAdapter(OriginatingAccountResponseType.Adapter.class)public enum OriginatingAccountResponseType {
  
  BREX_CASH("BREX_CASH");

  private String value;

  OriginatingAccountResponseType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static OriginatingAccountResponseType fromValue(String value) {
    for (OriginatingAccountResponseType b : OriginatingAccountResponseType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<OriginatingAccountResponseType> {
    @Override
    public void write(final JsonWriter jsonWriter, final OriginatingAccountResponseType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public OriginatingAccountResponseType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return OriginatingAccountResponseType.fromValue(value);
    }
  }
}

