/*
 * Payments API
 *  The payments API allows you to initiate and manage payments and vendors from your Brex business accounts. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PaymentAccountRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * UpdateVendorRequest
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class UpdateVendorRequest {
  public static final String SERIALIZED_NAME_COMPANY_NAME = "company_name";
  @SerializedName(SERIALIZED_NAME_COMPANY_NAME)
  private String companyName;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_PHONE = "phone";
  @SerializedName(SERIALIZED_NAME_PHONE)
  private String phone;

  public static final String SERIALIZED_NAME_PAYMENT_ACCOUNTS = "payment_accounts";
  @SerializedName(SERIALIZED_NAME_PAYMENT_ACCOUNTS)
  private List<PaymentAccountRequest> paymentAccounts = null;

  public static final String SERIALIZED_NAME_BENEFICIARY_NAME = "beneficiary_name";
  @SerializedName(SERIALIZED_NAME_BENEFICIARY_NAME)
  private String beneficiaryName;

  public UpdateVendorRequest() {
  }

  public UpdateVendorRequest companyName(String companyName) {
    
    
    
    
    this.companyName = companyName;
    return this;
  }

   /**
   * Name for vendor
   * @return companyName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name for vendor")

  public String getCompanyName() {
    return companyName;
  }


  public void setCompanyName(String companyName) {
    
    
    
    this.companyName = companyName;
  }


  public UpdateVendorRequest email(String email) {
    
    
    
    
    this.email = email;
    return this;
  }

   /**
   * Email for vendor
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Email for vendor")

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    
    
    
    this.email = email;
  }


  public UpdateVendorRequest phone(String phone) {
    
    
    
    
    this.phone = phone;
    return this;
  }

   /**
   * Phone number for vendor
   * @return phone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Phone number for vendor")

  public String getPhone() {
    return phone;
  }


  public void setPhone(String phone) {
    
    
    
    this.phone = phone;
  }


  public UpdateVendorRequest paymentAccounts(List<PaymentAccountRequest> paymentAccounts) {
    
    
    
    
    this.paymentAccounts = paymentAccounts;
    return this;
  }

  public UpdateVendorRequest addPaymentAccountsItem(PaymentAccountRequest paymentAccountsItem) {
    if (this.paymentAccounts == null) {
      this.paymentAccounts = new ArrayList<>();
    }
    this.paymentAccounts.add(paymentAccountsItem);
    return this;
  }

   /**
   * To update payment instruments, we require the entire payload for each payment instrument that is being updated. 
   * @return paymentAccounts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "To update payment instruments, we require the entire payload for each payment instrument that is being updated. ")

  public List<PaymentAccountRequest> getPaymentAccounts() {
    return paymentAccounts;
  }


  public void setPaymentAccounts(List<PaymentAccountRequest> paymentAccounts) {
    
    
    
    this.paymentAccounts = paymentAccounts;
  }


  public UpdateVendorRequest beneficiaryName(String beneficiaryName) {
    
    
    
    
    this.beneficiaryName = beneficiaryName;
    return this;
  }

   /**
   * Name for the Beneficiary
   * @return beneficiaryName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name for the Beneficiary")

  public String getBeneficiaryName() {
    return beneficiaryName;
  }


  public void setBeneficiaryName(String beneficiaryName) {
    
    
    
    this.beneficiaryName = beneficiaryName;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the UpdateVendorRequest instance itself
   */
  public UpdateVendorRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateVendorRequest updateVendorRequest = (UpdateVendorRequest) o;
    return Objects.equals(this.companyName, updateVendorRequest.companyName) &&
        Objects.equals(this.email, updateVendorRequest.email) &&
        Objects.equals(this.phone, updateVendorRequest.phone) &&
        Objects.equals(this.paymentAccounts, updateVendorRequest.paymentAccounts) &&
        Objects.equals(this.beneficiaryName, updateVendorRequest.beneficiaryName)&&
        Objects.equals(this.additionalProperties, updateVendorRequest.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyName, email, phone, paymentAccounts, beneficiaryName, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateVendorRequest {\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    paymentAccounts: ").append(toIndentedString(paymentAccounts)).append("\n");
    sb.append("    beneficiaryName: ").append(toIndentedString(beneficiaryName)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("company_name");
    openapiFields.add("email");
    openapiFields.add("phone");
    openapiFields.add("payment_accounts");
    openapiFields.add("beneficiary_name");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to UpdateVendorRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!UpdateVendorRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdateVendorRequest is not found in the empty JSON string", UpdateVendorRequest.openapiRequiredFields.toString()));
        }
      }
      if (!jsonObj.get("company_name").isJsonNull() && (jsonObj.get("company_name") != null && !jsonObj.get("company_name").isJsonNull()) && !jsonObj.get("company_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `company_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("company_name").toString()));
      }
      if (!jsonObj.get("email").isJsonNull() && (jsonObj.get("email") != null && !jsonObj.get("email").isJsonNull()) && !jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
      if (!jsonObj.get("phone").isJsonNull() && (jsonObj.get("phone") != null && !jsonObj.get("phone").isJsonNull()) && !jsonObj.get("phone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `phone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("phone").toString()));
      }
      if (jsonObj.get("payment_accounts") != null && !jsonObj.get("payment_accounts").isJsonNull()) {
        JsonArray jsonArraypaymentAccounts = jsonObj.getAsJsonArray("payment_accounts");
        if (jsonArraypaymentAccounts != null) {
          // ensure the json data is an array
          if (!jsonObj.get("payment_accounts").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `payment_accounts` to be an array in the JSON string but got `%s`", jsonObj.get("payment_accounts").toString()));
          }

          // validate the optional field `payment_accounts` (array)
          for (int i = 0; i < jsonArraypaymentAccounts.size(); i++) {
            PaymentAccountRequest.validateJsonObject(jsonArraypaymentAccounts.get(i).getAsJsonObject());
          };
        }
      }
      if (!jsonObj.get("beneficiary_name").isJsonNull() && (jsonObj.get("beneficiary_name") != null && !jsonObj.get("beneficiary_name").isJsonNull()) && !jsonObj.get("beneficiary_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `beneficiary_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("beneficiary_name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateVendorRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateVendorRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateVendorRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateVendorRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateVendorRequest>() {
           @Override
           public void write(JsonWriter out, UpdateVendorRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateVendorRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             UpdateVendorRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UpdateVendorRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UpdateVendorRequest
  * @throws IOException if the JSON string is invalid with respect to UpdateVendorRequest
  */
  public static UpdateVendorRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateVendorRequest.class);
  }

 /**
  * Convert an instance of UpdateVendorRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

