openapi: 3.0.1
info:
  contact:
    email: developer-access@brex.com
    name: Admin
    url: https://brex.com
  description: |2

    The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.
  title: Payments API
  version: "1.0"
  x-konfig-has-globally-required-security: true
servers:
- description: Production
  url: https://platform.brexapis.com
- description: "Staging (Note: This is not a sandbox. It will not work with customer\
    \ tokens.)"
  url: https://platform.staging.brexapps.com
security:
- OAuth2: []
tags:
- description: Endpoints to manage vendors
  name: Vendors
- description: "Endpoints to initiate transfers and view transfer statuses. Note that\
    \ for all transfer endpoints, the 'money' field is positive or unsigned for outgoing\
    \ transfers (debits), and negative for incoming transfers (credits)."
  name: Transfers
- description: Endpoint to view connected linked accounts
  name: Linked Accounts
paths:
  /v1/incoming_transfers:
    post:
      description: "\nThis endpoint creates a new incoming transfer. You may use use\
        \ any eligible bank account connection to fund (ACH Debit) \nany active Brex\
        \ business account.\n\n**Reminder**: You may not use the Brex API for any\
        \ activity that requires a license or registration from any \ngovernmental\
        \ authority without Brex's prior review and approval. This includes but is\
        \ not limited to any money services\nbusiness or money transmission activity.\n\
        \nPlease review the <a href=\"https://www.brex.com/legal/developer-portal/\"\
        >Brex Access Agreement</a> and contact us if \nyou have any questions.\n"
      operationId: Transfers_createIncomingTransfer
      security:
      - OAuth2:
        - incoming_transfers
      summary: |2

        Create incoming transfer
      tags:
      - Transfers
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v1-incoming_transfers
      x-content-type: application/json
      x-accepts: application/json
  /v1/linked_accounts:
    get:
      description: |2

        This endpoint lists all bank connections that are eligible to make ACH transfers to Brex business account
      operationId: LinkedAccounts_list
      security:
      - OAuth2:
        - linked_accounts.readonly
      summary: |2

        Lists linked accounts
      tags:
      - Linked Accounts
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v1-linked_accounts
      x-accepts: application/json
  /v1/transfers:
    get:
      description: |2

        This endpoint lists existing transfers for an account.

        Currently, the API can only return transfers for the following payment rails:
        - ACH
        - DOMESTIC_WIRE
        - CHEQUE
        - INTERNATIONAL_WIRE
      operationId: Transfers_list
      security:
      - OAuth2:
        - transfers.readonly
        - incoming_transfers
      summary: "\nLists transfers \n"
      tags:
      - Transfers
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v1-transfers
      x-accepts: application/json
    post:
      description: "\nThis endpoint creates a new transfer.\n\nCurrently, the API\
        \ can only create transfers for the following payment rails:\n- ACH\n- DOMESTIC_WIRE\n\
        - CHEQUE\n- INTERNATIONAL_WIRES (For vendors already created through dashboard.\
        \ Rate limited to 100/day - Please reach out to developer-support@brex.com\
        \ if you need to do more)\n\n**Transaction Descriptions**\n* For outgoing\
        \ check payments, a successful transfer will return a response containing\
        \ a description value with a format of `Check #<check number> to <recipient_name>\
        \ - <external_memo>`.\n* For book transfers (from one Brex Business account\
        \ to another), the recipient value will have a format of `<customer_account.dba_name>\
        \ - <external_memo>` and the sender will have a format of `<target customer\
        \ account's dba name> - <external_memo>`.\n* For other payment rails, the\
        \ format will be `<counterparty_name> - <external_memo>`, where Counterparty\
        \ name is `payment_instrument.beneficiary_name` or `contact.name`\nFor vendors\
        \ created from the Payments API, the `counterparty_name` will be the `company_name`\
        \ [field](https://developer.brex.com/openapi/payments_api/).\n\n**Reminder**:\
        \ You may not use the Brex API for any activity that requires a license or\
        \ registration from any \ngovernmental authority without Brex's prior review\
        \ and approval. This includes but is not limited to any money services\nbusiness\
        \ or money transmission activity.\n\nPlease review the <a href=\"https://www.brex.com/legal/developer-portal/\"\
        >Brex Access Agreement</a> and contact us if \nyou have any questions.\n"
      operationId: Transfers_createTransfer
      security:
      - OAuth2:
        - transfers
      summary: |2

        Create transfer
      tags:
      - Transfers
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v1-transfers
      x-content-type: application/json
      x-accepts: application/json
  /v1/transfers/{id}:
    get:
      description: |2

        This endpoint gets a transfer by ID.

        Currently, the API can only return transfers for the following payment rails:
        - ACH
        - DOMESTIC_WIRE
        - CHEQUE
        - INTERNATIONAL_WIRE
      operationId: Transfers_getById
      security:
      - OAuth2:
        - transfers.readonly
        - incoming_transfers
      summary: |2

        Get transfer
      tags:
      - Transfers
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v1-transfers-id
      x-accepts: application/json
  /v1/vendors:
    get:
      description: |2

        This endpoint lists all existing vendors for an account.
        Takes an optional parameter to match by vendor name.
      operationId: Vendors_list
      security:
      - OAuth2:
        - vendors.readonly
      summary: "\nLists vendors \n"
      tags:
      - Vendors
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v1-vendors
      x-accepts: application/json
    post:
      description: |2

        This endpoint creates a new vendor.
      operationId: Vendors_createNewVendor
      security:
      - OAuth2:
        - vendors
      summary: |2

        Create vendor
      tags:
      - Vendors
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v1-vendors
      x-content-type: application/json
      x-accepts: application/json
  /v1/vendors/{id}:
    delete:
      description: |2

        This endpoint deletes a vendor by ID.
      operationId: Vendors_deleteVendorById
      security:
      - OAuth2:
        - vendors
      summary: |2

        Delete vendor.
      tags:
      - Vendors
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--v1-vendors-id
      x-accepts: application/json
    get:
      description: |2

        This endpoint gets a vendor by ID.
      operationId: Vendors_getById
      security:
      - OAuth2:
        - vendors.readonly
      summary: |2

        Get vendor
      tags:
      - Vendors
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v1-vendors-id
      x-accepts: application/json
    put:
      description: |2

            Updates an existing vendor by ID.
      operationId: Vendors_updateById
      security:
      - OAuth2:
        - vendors
      summary: Update vendor
      tags:
      - Vendors
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--v1-vendors-id
      x-content-type: application/json
      x-accepts: application/json
components:
  securitySchemes:
    OAuth2:
      description: OAuth2 security scheme
      flows:
        authorizationCode:
          authorizationUrl: https://accounts-api.brex.com/oauth2/default/v1/authorize
          scopes:
            openid: openid
            offline_access: offline access
            vendors: View and manage vendor data
            vendors.readonly: View vendor data
            transfers: View and manage transfer data
            transfers.readonly: View transfer data
            incoming_transfers: View and manage incoming transfer data
            linked_accounts.readonly: View linked accounts
          tokenUrl: https://accounts-api.brex.com/oauth2/default/v1/token
      type: oauth2
      x-konfig-globally-required-security: true
x-explorer-enabled: false

